site_name: SeaTAK
site_url: https://seatak.readthedocs.io/
repo_url: https://github.com/snstac/seatak
site_description: SeaTAK Documentation
site_author: Greg Albrecht <gba@snstac.com>
copyright: Copyright 2023 Sensors & Signals LLC

theme:
  name: material
  highlightjs: true

plugins:
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - toc:
      permalink: True
